import type { RenderTypeFn } from './RenderHelpers';
import {
  renderBlockCocoa,
  renderBlockCrops,
  renderBlockFire,
  renderBlockLadder,
  renderBlockLever,
  renderBlockLilyPad,
  renderBlockMinecartTrack,
  renderBlockRedstoneWire,
  renderBlockStem,
  renderBlockTripWire,
  renderBlockTripWireSource,
  renderBlockVine,
} from './RenderShapes';
import {
  renderBlockAnvil,
  renderBlockBeacon,
  renderBlockBed,
  renderBlockBrewingStand,
  renderBlockCauldron,
  renderBlockComparator,
  renderBlockDoor,
  renderBlockDragonEgg,
  renderBlockEndPortalFrame,
  renderBlockFence,
  renderBlockFenceGate,
  renderBlockFlowerpot,
  renderBlockHopper,
  renderBlockPane,
  renderBlockQuartz,
  renderBlockRedstoneLogic,
  renderBlockRepeater,
  renderBlockStairs,
  renderBlockWall,
  renderPistonBase,
  renderPistonExtension,
} from './RenderStructures';

/**
 * Render type -> renderer for every type of 1.5.2's renderBlockByRenderType that RenderBlocks
 * does not draw itself (0 standard, 1 crossed squares, 2 torch, 4 fluids, 13 cactus, 31 logs).
 * Type 22 (chests) has no block renderer: its tile-entity renderer draws it.
 */
export const RENDER_TYPES: ReadonlyMap<number, RenderTypeFn> = new Map<number, RenderTypeFn>([
  [3, renderBlockFire],
  [5, renderBlockRedstoneWire],
  [6, renderBlockCrops],
  [7, renderBlockDoor],
  [8, renderBlockLadder],
  [9, renderBlockMinecartTrack],
  [10, renderBlockStairs],
  [11, renderBlockFence],
  [12, renderBlockLever],
  [14, renderBlockBed],
  [15, renderBlockRepeater],
  [16, (rb, b, x, y, z) => renderPistonBase(rb, b, x, y, z, false)],
  [17, (rb, b, x, y, z) => renderPistonExtension(rb, b, x, y, z, true)],
  [18, renderBlockPane],
  [19, renderBlockStem],
  [20, renderBlockVine],
  [21, renderBlockFenceGate],
  [23, renderBlockLilyPad],
  [24, renderBlockCauldron],
  [25, renderBlockBrewingStand],
  [26, renderBlockEndPortalFrame],
  [27, renderBlockDragonEgg],
  [28, renderBlockCocoa],
  [29, renderBlockTripWireSource],
  [30, renderBlockTripWire],
  [32, renderBlockWall],
  [33, renderBlockFlowerpot],
  [34, renderBlockBeacon],
  [35, renderBlockAnvil],
  [36, renderBlockRedstoneLogic],
  [37, renderBlockComparator],
  [38, renderBlockHopper],
  [39, renderBlockQuartz],
]);
